"""
Wavefront OBJ / MTL export for voxelised 3-D geometry arrays.

The exported mesh contains only **exposed boundary faces** (faces between
voxels of different material IDs, or domain-edge faces), keeping the file
compact enough for interactive Blender sessions.

The MTL file writes ``Kd`` lines in the same format that the SeidarT
``Domain3D._parse_mtl_kd()`` reader expects, so the round-trip
``geometry → OBJ → Blender → OBJ → Domain3D`` is seamless.
"""

import numpy as np

# Default distinguishable palette (12 colours).  Index by material_id % len.
_DEFAULT_PALETTE = [
    (0.80, 0.80, 0.80),  # 0  light grey  (air / background)
    (0.55, 0.27, 0.07),  # 1  brown       (rock / sediment)
    (0.50, 0.82, 0.96),  # 2  ice blue
    (0.00, 0.00, 0.80),  # 3  dark blue    (water)
    (0.20, 0.60, 0.20),  # 4  green
    (0.93, 0.79, 0.00),  # 5  gold
    (0.85, 0.33, 0.10),  # 6  orange
    (0.58, 0.00, 0.83),  # 7  purple
    (0.96, 0.26, 0.26),  # 8  red
    (0.00, 0.50, 0.50),  # 9  teal
    (0.70, 0.70, 0.30),  # 10 olive
    (0.40, 0.40, 0.40),  # 11 dark grey
]


def _rgb_string_to_float(rgb_str: str):
    """Convert ``'R/G/B'`` (0-255) string to (r, g, b) floats in [0, 1]."""
    parts = rgb_str.split("/")
    return tuple(int(p) / 255.0 for p in parts)


def geometry_to_obj(
        geometry_3d: np.ndarray,
        obj_path: str = "domain.obj",
        *,
        dx: float = 1.0,
        dy: float = 1.0,
        dz: float = 1.0,
        material_names: dict = None,
        material_colours: dict = None,
        skip_ids: set = None,
    ) -> None:
    """Export a 3-D integer geometry array as Wavefront OBJ + MTL files.

    Only **exposed boundary faces** (faces between two voxels with different
    material IDs, or faces on the domain boundary) are emitted, so the
    resulting mesh is compact and suitable for Blender visualisation.

    After editing in Blender the user can re-export OBJ + MTL and feed them
    into ``seidart.routines.classes.Domain3D`` / ``VolumeBuilder`` for
    re-voxelisation.

    Parameters
    ----------
    geometry_3d : ndarray, shape (nx, ny, nz)
        Integer material-ID array (SeidarT convention).
    obj_path : str, optional
        Output ``.obj`` file path.  The ``.mtl`` file is written alongside
        with the same base name.
    dx, dy, dz : float, optional
        Grid spacings in metres — used to set vertex coordinates so the
        mesh has physical dimensions.
    material_names : dict, optional
        ``{material_id: name_string}``.  If omitted, materials are named
        ``material_0``, ``material_1``, etc.
    material_colours : dict, optional
        ``{material_id: (r, g, b)}`` with floats in [0, 1], **or**
        ``{material_id: 'R/G/B'}`` strings (0-255).  If omitted, a
        built-in palette is used.
    skip_ids : set of int, optional
        Material IDs whose faces should **not** be written (e.g. ``{0}``
        to suppress the air/background volume and see only the subsurface).
    """
    if geometry_3d.ndim != 3:
        raise ValueError("geometry_3d must be 3-D, shape (nx, ny, nz).")

    nx, ny, nz = geometry_3d.shape
    skip_ids = set(skip_ids or [])
    unique_ids = sorted(set(np.unique(geometry_3d)) - skip_ids)

    if material_names is None:
        material_names = {}
    if material_colours is None:
        material_colours = {}

    def _get_name(mid):
        return material_names.get(mid, f"material_{mid}")

    def _get_colour(mid):
        c = material_colours.get(mid)
        if c is None:
            return _DEFAULT_PALETTE[mid % len(_DEFAULT_PALETTE)]
        if isinstance(c, str):
            return _rgb_string_to_float(c)
        return tuple(c)

    # ------------------------------------------------------------------
    # Write MTL
    # ------------------------------------------------------------------
    base = obj_path.rsplit(".", 1)[0]
    mtl_path = base + ".mtl"
    mtl_basename = mtl_path.rsplit("/", 1)[-1]

    with open(mtl_path, "w") as fm:
        fm.write("# Generated by surface_roughness.geometry_to_obj\n\n")
        for mid in unique_ids:
            name = _get_name(mid)
            r, g, b = _get_colour(mid)
            fm.write(f"newmtl {name}\n")
            fm.write(f"Kd {r:.4f} {g:.4f} {b:.4f}\n")
            fm.write(f"Ka {r * 0.2:.4f} {g * 0.2:.4f} {b * 0.2:.4f}\n")
            fm.write("Ks 0.1000 0.1000 0.1000\n")
            fm.write("Ns 50.0\n")
            fm.write("d 1.0\n")
            fm.write("illum 2\n\n")

    # ------------------------------------------------------------------
    # Collect exposed faces per material
    # ------------------------------------------------------------------
    mat_faces = {mid: [] for mid in unique_ids}

    # Pad with -1 on every face so boundary faces are always detected
    padded = np.full((nx + 2, ny + 2, nz + 2), -1, dtype=geometry_3d.dtype)
    padded[1:-1, 1:-1, 1:-1] = geometry_3d

    for mid in unique_ids:
        mask = padded == mid

        # +x face
        exposed = mask[1:-1, 1:-1, 1:-1] & (padded[2:, 1:-1, 1:-1] != mid)
        ii, jj, kk = np.where(exposed)
        for i, j, k in zip(ii, jj, kk):
            x = (i + 1) * dx
            mat_faces[mid].append((
                (x, j*dy, k*dz), (x, (j+1)*dy, k*dz),
                (x, (j+1)*dy, (k+1)*dz), (x, j*dy, (k+1)*dz),
            ))

        # -x face
        exposed = mask[1:-1, 1:-1, 1:-1] & (padded[:-2, 1:-1, 1:-1] != mid)
        ii, jj, kk = np.where(exposed)
        for i, j, k in zip(ii, jj, kk):
            x = i * dx
            mat_faces[mid].append((
                (x, j*dy, k*dz), (x, j*dy, (k+1)*dz),
                (x, (j+1)*dy, (k+1)*dz), (x, (j+1)*dy, k*dz),
            ))

        # +y face
        exposed = mask[1:-1, 1:-1, 1:-1] & (padded[1:-1, 2:, 1:-1] != mid)
        ii, jj, kk = np.where(exposed)
        for i, j, k in zip(ii, jj, kk):
            y = (j + 1) * dy
            mat_faces[mid].append((
                (i*dx, y, k*dz), (i*dx, y, (k+1)*dz),
                ((i+1)*dx, y, (k+1)*dz), ((i+1)*dx, y, k*dz),
            ))

        # -y face
        exposed = mask[1:-1, 1:-1, 1:-1] & (padded[1:-1, :-2, 1:-1] != mid)
        ii, jj, kk = np.where(exposed)
        for i, j, k in zip(ii, jj, kk):
            y = j * dy
            mat_faces[mid].append((
                (i*dx, y, k*dz), ((i+1)*dx, y, k*dz),
                ((i+1)*dx, y, (k+1)*dz), (i*dx, y, (k+1)*dz),
            ))

        # +z face
        exposed = mask[1:-1, 1:-1, 1:-1] & (padded[1:-1, 1:-1, 2:] != mid)
        ii, jj, kk = np.where(exposed)
        for i, j, k in zip(ii, jj, kk):
            z = (k + 1) * dz
            mat_faces[mid].append((
                (i*dx, j*dy, z), ((i+1)*dx, j*dy, z),
                ((i+1)*dx, (j+1)*dy, z), (i*dx, (j+1)*dy, z),
            ))

        # -z face
        exposed = mask[1:-1, 1:-1, 1:-1] & (padded[1:-1, 1:-1, :-2] != mid)
        ii, jj, kk = np.where(exposed)
        for i, j, k in zip(ii, jj, kk):
            z = k * dz
            mat_faces[mid].append((
                (i*dx, j*dy, z), (i*dx, (j+1)*dy, z),
                ((i+1)*dx, (j+1)*dy, z), ((i+1)*dx, j*dy, z),
            ))

    # ------------------------------------------------------------------
    # Write OBJ — deduplicate vertices globally
    # ------------------------------------------------------------------
    vert_map = {}
    verts = []

    def _vert_index(v):
        key = (round(v[0], 8), round(v[1], 8), round(v[2], 8))
        if key not in vert_map:
            vert_map[key] = len(verts) + 1  # OBJ is 1-indexed
            verts.append(key)
        return vert_map[key]

    indexed_faces = {}
    for mid in unique_ids:
        indexed_faces[mid] = [
            tuple(_vert_index(v) for v in quad)
            for quad in mat_faces[mid]
        ]

    total_faces = sum(len(fl) for fl in indexed_faces.values())
    print(
        f"geometry_to_obj: {len(verts)} vertices, {total_faces} faces, "
        f"{len(unique_ids)} materials"
    )

    with open(obj_path, "w") as fo:
        fo.write("# Generated by surface_roughness.geometry_to_obj\n")
        fo.write(f"mtllib {mtl_basename}\n\n")

        for x, y, z in verts:
            fo.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
        fo.write("\n")

        for mid in unique_ids:
            name = _get_name(mid)
            fo.write(f"g {name}\n")
            fo.write(f"usemtl {name}\n")
            for f in indexed_faces[mid]:
                fo.write(f"f {f[0]} {f[1]} {f[2]} {f[3]}\n")
            fo.write("\n")

    print(f"Wrote {obj_path} and {mtl_path}")
